// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bnema/waymon/internal/adapters/in/cli"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIPCClient creates a new instance of MockIPCClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPCClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPCClient {
	mock := &MockIPCClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPCClient is an autogenerated mock type for the IPCClient type
type MockIPCClient struct {
	mock.Mock
}

type MockIPCClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPCClient) EXPECT() *MockIPCClient_Expecter {
	return &MockIPCClient_Expecter{mock: &_m.Mock}
}

// IsRunning provides a mock function for the type MockIPCClient
func (_mock *MockIPCClient) IsRunning() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsRunning")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockIPCClient_IsRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRunning'
type MockIPCClient_IsRunning_Call struct {
	*mock.Call
}

// IsRunning is a helper method to define mock.On call
func (_e *MockIPCClient_Expecter) IsRunning() *MockIPCClient_IsRunning_Call {
	return &MockIPCClient_IsRunning_Call{Call: _e.mock.On("IsRunning")}
}

func (_c *MockIPCClient_IsRunning_Call) Run(run func()) *MockIPCClient_IsRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPCClient_IsRunning_Call) Return(b bool) *MockIPCClient_IsRunning_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockIPCClient_IsRunning_Call) RunAndReturn(run func() bool) *MockIPCClient_IsRunning_Call {
	_c.Call.Return(run)
	return _c
}

// SendConnect provides a mock function for the type MockIPCClient
func (_mock *MockIPCClient) SendConnect(slot int32) (*cli.StatusResponse, error) {
	ret := _mock.Called(slot)

	if len(ret) == 0 {
		panic("no return value specified for SendConnect")
	}

	var r0 *cli.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int32) (*cli.StatusResponse, error)); ok {
		return returnFunc(slot)
	}
	if returnFunc, ok := ret.Get(0).(func(int32) *cli.StatusResponse); ok {
		r0 = returnFunc(slot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cli.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int32) error); ok {
		r1 = returnFunc(slot)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPCClient_SendConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendConnect'
type MockIPCClient_SendConnect_Call struct {
	*mock.Call
}

// SendConnect is a helper method to define mock.On call
//   - slot int32
func (_e *MockIPCClient_Expecter) SendConnect(slot interface{}) *MockIPCClient_SendConnect_Call {
	return &MockIPCClient_SendConnect_Call{Call: _e.mock.On("SendConnect", slot)}
}

func (_c *MockIPCClient_SendConnect_Call) Run(run func(slot int32)) *MockIPCClient_SendConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int32
		if args[0] != nil {
			arg0 = args[0].(int32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPCClient_SendConnect_Call) Return(statusResponse *cli.StatusResponse, err error) *MockIPCClient_SendConnect_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *MockIPCClient_SendConnect_Call) RunAndReturn(run func(slot int32) (*cli.StatusResponse, error)) *MockIPCClient_SendConnect_Call {
	_c.Call.Return(run)
	return _c
}

// SendRelease provides a mock function for the type MockIPCClient
func (_mock *MockIPCClient) SendRelease() (*cli.StatusResponse, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendRelease")
	}

	var r0 *cli.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*cli.StatusResponse, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *cli.StatusResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cli.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPCClient_SendRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRelease'
type MockIPCClient_SendRelease_Call struct {
	*mock.Call
}

// SendRelease is a helper method to define mock.On call
func (_e *MockIPCClient_Expecter) SendRelease() *MockIPCClient_SendRelease_Call {
	return &MockIPCClient_SendRelease_Call{Call: _e.mock.On("SendRelease")}
}

func (_c *MockIPCClient_SendRelease_Call) Run(run func()) *MockIPCClient_SendRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPCClient_SendRelease_Call) Return(statusResponse *cli.StatusResponse, err error) *MockIPCClient_SendRelease_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *MockIPCClient_SendRelease_Call) RunAndReturn(run func() (*cli.StatusResponse, error)) *MockIPCClient_SendRelease_Call {
	_c.Call.Return(run)
	return _c
}

// SendStatus provides a mock function for the type MockIPCClient
func (_mock *MockIPCClient) SendStatus() (*cli.StatusResponse, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendStatus")
	}

	var r0 *cli.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*cli.StatusResponse, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *cli.StatusResponse); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cli.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPCClient_SendStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStatus'
type MockIPCClient_SendStatus_Call struct {
	*mock.Call
}

// SendStatus is a helper method to define mock.On call
func (_e *MockIPCClient_Expecter) SendStatus() *MockIPCClient_SendStatus_Call {
	return &MockIPCClient_SendStatus_Call{Call: _e.mock.On("SendStatus")}
}

func (_c *MockIPCClient_SendStatus_Call) Run(run func()) *MockIPCClient_SendStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPCClient_SendStatus_Call) Return(statusResponse *cli.StatusResponse, err error) *MockIPCClient_SendStatus_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *MockIPCClient_SendStatus_Call) RunAndReturn(run func() (*cli.StatusResponse, error)) *MockIPCClient_SendStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SendStop provides a mock function for the type MockIPCClient
func (_mock *MockIPCClient) SendStop() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendStop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPCClient_SendStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendStop'
type MockIPCClient_SendStop_Call struct {
	*mock.Call
}

// SendStop is a helper method to define mock.On call
func (_e *MockIPCClient_Expecter) SendStop() *MockIPCClient_SendStop_Call {
	return &MockIPCClient_SendStop_Call{Call: _e.mock.On("SendStop")}
}

func (_c *MockIPCClient_SendStop_Call) Run(run func()) *MockIPCClient_SendStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPCClient_SendStop_Call) Return(err error) *MockIPCClient_SendStop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPCClient_SendStop_Call) RunAndReturn(run func() error) *MockIPCClient_SendStop_Call {
	_c.Call.Return(run)
	return _c
}

// SendSwitch provides a mock function for the type MockIPCClient
func (_mock *MockIPCClient) SendSwitch(action cli.SwitchAction) (*cli.StatusResponse, error) {
	ret := _mock.Called(action)

	if len(ret) == 0 {
		panic("no return value specified for SendSwitch")
	}

	var r0 *cli.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(cli.SwitchAction) (*cli.StatusResponse, error)); ok {
		return returnFunc(action)
	}
	if returnFunc, ok := ret.Get(0).(func(cli.SwitchAction) *cli.StatusResponse); ok {
		r0 = returnFunc(action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cli.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(cli.SwitchAction) error); ok {
		r1 = returnFunc(action)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPCClient_SendSwitch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSwitch'
type MockIPCClient_SendSwitch_Call struct {
	*mock.Call
}

// SendSwitch is a helper method to define mock.On call
//   - action cli.SwitchAction
func (_e *MockIPCClient_Expecter) SendSwitch(action interface{}) *MockIPCClient_SendSwitch_Call {
	return &MockIPCClient_SendSwitch_Call{Call: _e.mock.On("SendSwitch", action)}
}

func (_c *MockIPCClient_SendSwitch_Call) Run(run func(action cli.SwitchAction)) *MockIPCClient_SendSwitch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cli.SwitchAction
		if args[0] != nil {
			arg0 = args[0].(cli.SwitchAction)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPCClient_SendSwitch_Call) Return(statusResponse *cli.StatusResponse, err error) *MockIPCClient_SendSwitch_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *MockIPCClient_SendSwitch_Call) RunAndReturn(run func(action cli.SwitchAction) (*cli.StatusResponse, error)) *MockIPCClient_SendSwitch_Call {
	_c.Call.Return(run)
	return _c
}
