// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/waymon/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientUseCase creates a new instance of MockClientUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientUseCase {
	mock := &MockClientUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientUseCase is an autogenerated mock type for the ClientUseCase type
type MockClientUseCase struct {
	mock.Mock
}

type MockClientUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientUseCase) EXPECT() *MockClientUseCase_Expecter {
	return &MockClientUseCase_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Connect(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientUseCase_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockClientUseCase_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientUseCase_Expecter) Connect(ctx interface{}) *MockClientUseCase_Connect_Call {
	return &MockClientUseCase_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *MockClientUseCase_Connect_Call) Run(run func(ctx context.Context)) *MockClientUseCase_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Connect_Call) Return(err error) *MockClientUseCase_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientUseCase_Connect_Call) RunAndReturn(run func(ctx context.Context) error) *MockClientUseCase_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// Disconnect provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) Disconnect(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Disconnect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientUseCase_Disconnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disconnect'
type MockClientUseCase_Disconnect_Call struct {
	*mock.Call
}

// Disconnect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientUseCase_Expecter) Disconnect(ctx interface{}) *MockClientUseCase_Disconnect_Call {
	return &MockClientUseCase_Disconnect_Call{Call: _e.mock.On("Disconnect", ctx)}
}

func (_c *MockClientUseCase_Disconnect_Call) Run(run func(ctx context.Context)) *MockClientUseCase_Disconnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientUseCase_Disconnect_Call) Return(err error) *MockClientUseCase_Disconnect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientUseCase_Disconnect_Call) RunAndReturn(run func(ctx context.Context) error) *MockClientUseCase_Disconnect_Call {
	_c.Call.Return(run)
	return _c
}

// GetControlStatus provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) GetControlStatus(ctx context.Context) domain.ControlStatus {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetControlStatus")
	}

	var r0 domain.ControlStatus
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.ControlStatus); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.ControlStatus)
	}
	return r0
}

// MockClientUseCase_GetControlStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetControlStatus'
type MockClientUseCase_GetControlStatus_Call struct {
	*mock.Call
}

// GetControlStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClientUseCase_Expecter) GetControlStatus(ctx interface{}) *MockClientUseCase_GetControlStatus_Call {
	return &MockClientUseCase_GetControlStatus_Call{Call: _e.mock.On("GetControlStatus", ctx)}
}

func (_c *MockClientUseCase_GetControlStatus_Call) Run(run func(ctx context.Context)) *MockClientUseCase_GetControlStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientUseCase_GetControlStatus_Call) Return(controlStatus domain.ControlStatus) *MockClientUseCase_GetControlStatus_Call {
	_c.Call.Return(controlStatus)
	return _c
}

func (_c *MockClientUseCase_GetControlStatus_Call) RunAndReturn(run func(ctx context.Context) domain.ControlStatus) *MockClientUseCase_GetControlStatus_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) IsConnected() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockClientUseCase_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockClientUseCase_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MockClientUseCase_Expecter) IsConnected() *MockClientUseCase_IsConnected_Call {
	return &MockClientUseCase_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MockClientUseCase_IsConnected_Call) Run(run func()) *MockClientUseCase_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientUseCase_IsConnected_Call) Return(b bool) *MockClientUseCase_IsConnected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockClientUseCase_IsConnected_Call) RunAndReturn(run func() bool) *MockClientUseCase_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// SetOnConnectionStateChanged provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) SetOnConnectionStateChanged(callback func(connected bool, serverName string)) {
	_mock.Called(callback)
	return
}

// MockClientUseCase_SetOnConnectionStateChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnConnectionStateChanged'
type MockClientUseCase_SetOnConnectionStateChanged_Call struct {
	*mock.Call
}

// SetOnConnectionStateChanged is a helper method to define mock.On call
//   - callback func(connected bool, serverName string)
func (_e *MockClientUseCase_Expecter) SetOnConnectionStateChanged(callback interface{}) *MockClientUseCase_SetOnConnectionStateChanged_Call {
	return &MockClientUseCase_SetOnConnectionStateChanged_Call{Call: _e.mock.On("SetOnConnectionStateChanged", callback)}
}

func (_c *MockClientUseCase_SetOnConnectionStateChanged_Call) Run(run func(callback func(connected bool, serverName string))) *MockClientUseCase_SetOnConnectionStateChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(connected bool, serverName string)
		if args[0] != nil {
			arg0 = args[0].(func(connected bool, serverName string))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientUseCase_SetOnConnectionStateChanged_Call) Return() *MockClientUseCase_SetOnConnectionStateChanged_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientUseCase_SetOnConnectionStateChanged_Call) RunAndReturn(run func(callback func(connected bool, serverName string))) *MockClientUseCase_SetOnConnectionStateChanged_Call {
	_c.Run(run)
	return _c
}

// SetOnControlChanged provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) SetOnControlChanged(callback func(status domain.ControlStatus)) {
	_mock.Called(callback)
	return
}

// MockClientUseCase_SetOnControlChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnControlChanged'
type MockClientUseCase_SetOnControlChanged_Call struct {
	*mock.Call
}

// SetOnControlChanged is a helper method to define mock.On call
//   - callback func(status domain.ControlStatus)
func (_e *MockClientUseCase_Expecter) SetOnControlChanged(callback interface{}) *MockClientUseCase_SetOnControlChanged_Call {
	return &MockClientUseCase_SetOnControlChanged_Call{Call: _e.mock.On("SetOnControlChanged", callback)}
}

func (_c *MockClientUseCase_SetOnControlChanged_Call) Run(run func(callback func(status domain.ControlStatus))) *MockClientUseCase_SetOnControlChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(status domain.ControlStatus)
		if args[0] != nil {
			arg0 = args[0].(func(status domain.ControlStatus))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientUseCase_SetOnControlChanged_Call) Return() *MockClientUseCase_SetOnControlChanged_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientUseCase_SetOnControlChanged_Call) RunAndReturn(run func(callback func(status domain.ControlStatus))) *MockClientUseCase_SetOnControlChanged_Call {
	_c.Run(run)
	return _c
}

// SetServerAddress provides a mock function for the type MockClientUseCase
func (_mock *MockClientUseCase) SetServerAddress(addr string) {
	_mock.Called(addr)
	return
}

// MockClientUseCase_SetServerAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetServerAddress'
type MockClientUseCase_SetServerAddress_Call struct {
	*mock.Call
}

// SetServerAddress is a helper method to define mock.On call
//   - addr string
func (_e *MockClientUseCase_Expecter) SetServerAddress(addr interface{}) *MockClientUseCase_SetServerAddress_Call {
	return &MockClientUseCase_SetServerAddress_Call{Call: _e.mock.On("SetServerAddress", addr)}
}

func (_c *MockClientUseCase_SetServerAddress_Call) Run(run func(addr string)) *MockClientUseCase_SetServerAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClientUseCase_SetServerAddress_Call) Return() *MockClientUseCase_SetServerAddress_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClientUseCase_SetServerAddress_Call) RunAndReturn(run func(addr string)) *MockClientUseCase_SetServerAddress_Call {
	_c.Run(run)
	return _c
}
