// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/waymon/internal/boundaries/in"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIPCHandler creates a new instance of MockIPCHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPCHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPCHandler {
	mock := &MockIPCHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPCHandler is an autogenerated mock type for the IPCHandler type
type MockIPCHandler struct {
	mock.Mock
}

type MockIPCHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPCHandler) EXPECT() *MockIPCHandler_Expecter {
	return &MockIPCHandler_Expecter{mock: &_m.Mock}
}

// HandleConnect provides a mock function for the type MockIPCHandler
func (_mock *MockIPCHandler) HandleConnect(ctx context.Context, slot int32) (*in.StatusResponse, error) {
	ret := _mock.Called(ctx, slot)

	if len(ret) == 0 {
		panic("no return value specified for HandleConnect")
	}

	var r0 *in.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (*in.StatusResponse, error)); ok {
		return returnFunc(ctx, slot)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) *in.StatusResponse); ok {
		r0 = returnFunc(ctx, slot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*in.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, slot)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPCHandler_HandleConnect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleConnect'
type MockIPCHandler_HandleConnect_Call struct {
	*mock.Call
}

// HandleConnect is a helper method to define mock.On call
//   - ctx context.Context
//   - slot int32
func (_e *MockIPCHandler_Expecter) HandleConnect(ctx interface{}, slot interface{}) *MockIPCHandler_HandleConnect_Call {
	return &MockIPCHandler_HandleConnect_Call{Call: _e.mock.On("HandleConnect", ctx, slot)}
}

func (_c *MockIPCHandler_HandleConnect_Call) Run(run func(ctx context.Context, slot int32)) *MockIPCHandler_HandleConnect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPCHandler_HandleConnect_Call) Return(statusResponse *in.StatusResponse, err error) *MockIPCHandler_HandleConnect_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *MockIPCHandler_HandleConnect_Call) RunAndReturn(run func(ctx context.Context, slot int32) (*in.StatusResponse, error)) *MockIPCHandler_HandleConnect_Call {
	_c.Call.Return(run)
	return _c
}

// HandleRelease provides a mock function for the type MockIPCHandler
func (_mock *MockIPCHandler) HandleRelease(ctx context.Context) (*in.StatusResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HandleRelease")
	}

	var r0 *in.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*in.StatusResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *in.StatusResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*in.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPCHandler_HandleRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRelease'
type MockIPCHandler_HandleRelease_Call struct {
	*mock.Call
}

// HandleRelease is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPCHandler_Expecter) HandleRelease(ctx interface{}) *MockIPCHandler_HandleRelease_Call {
	return &MockIPCHandler_HandleRelease_Call{Call: _e.mock.On("HandleRelease", ctx)}
}

func (_c *MockIPCHandler_HandleRelease_Call) Run(run func(ctx context.Context)) *MockIPCHandler_HandleRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPCHandler_HandleRelease_Call) Return(statusResponse *in.StatusResponse, err error) *MockIPCHandler_HandleRelease_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *MockIPCHandler_HandleRelease_Call) RunAndReturn(run func(ctx context.Context) (*in.StatusResponse, error)) *MockIPCHandler_HandleRelease_Call {
	_c.Call.Return(run)
	return _c
}

// HandleStatus provides a mock function for the type MockIPCHandler
func (_mock *MockIPCHandler) HandleStatus(ctx context.Context) (*in.StatusResponse, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HandleStatus")
	}

	var r0 *in.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*in.StatusResponse, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *in.StatusResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*in.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPCHandler_HandleStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleStatus'
type MockIPCHandler_HandleStatus_Call struct {
	*mock.Call
}

// HandleStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPCHandler_Expecter) HandleStatus(ctx interface{}) *MockIPCHandler_HandleStatus_Call {
	return &MockIPCHandler_HandleStatus_Call{Call: _e.mock.On("HandleStatus", ctx)}
}

func (_c *MockIPCHandler_HandleStatus_Call) Run(run func(ctx context.Context)) *MockIPCHandler_HandleStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPCHandler_HandleStatus_Call) Return(statusResponse *in.StatusResponse, err error) *MockIPCHandler_HandleStatus_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *MockIPCHandler_HandleStatus_Call) RunAndReturn(run func(ctx context.Context) (*in.StatusResponse, error)) *MockIPCHandler_HandleStatus_Call {
	_c.Call.Return(run)
	return _c
}

// HandleSwitch provides a mock function for the type MockIPCHandler
func (_mock *MockIPCHandler) HandleSwitch(ctx context.Context, action in.SwitchAction) (*in.StatusResponse, error) {
	ret := _mock.Called(ctx, action)

	if len(ret) == 0 {
		panic("no return value specified for HandleSwitch")
	}

	var r0 *in.StatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, in.SwitchAction) (*in.StatusResponse, error)); ok {
		return returnFunc(ctx, action)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, in.SwitchAction) *in.StatusResponse); ok {
		r0 = returnFunc(ctx, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*in.StatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, in.SwitchAction) error); ok {
		r1 = returnFunc(ctx, action)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPCHandler_HandleSwitch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSwitch'
type MockIPCHandler_HandleSwitch_Call struct {
	*mock.Call
}

// HandleSwitch is a helper method to define mock.On call
//   - ctx context.Context
//   - action in.SwitchAction
func (_e *MockIPCHandler_Expecter) HandleSwitch(ctx interface{}, action interface{}) *MockIPCHandler_HandleSwitch_Call {
	return &MockIPCHandler_HandleSwitch_Call{Call: _e.mock.On("HandleSwitch", ctx, action)}
}

func (_c *MockIPCHandler_HandleSwitch_Call) Run(run func(ctx context.Context, action in.SwitchAction)) *MockIPCHandler_HandleSwitch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 in.SwitchAction
		if args[1] != nil {
			arg1 = args[1].(in.SwitchAction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPCHandler_HandleSwitch_Call) Return(statusResponse *in.StatusResponse, err error) *MockIPCHandler_HandleSwitch_Call {
	_c.Call.Return(statusResponse, err)
	return _c
}

func (_c *MockIPCHandler_HandleSwitch_Call) RunAndReturn(run func(ctx context.Context, action in.SwitchAction) (*in.StatusResponse, error)) *MockIPCHandler_HandleSwitch_Call {
	_c.Call.Return(run)
	return _c
}
