// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bnema/waymon/internal/boundaries/out"
	"github.com/bnema/waymon/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerUseCase creates a new instance of MockServerUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerUseCase {
	mock := &MockServerUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerUseCase is an autogenerated mock type for the ServerUseCase type
type MockServerUseCase struct {
	mock.Mock
}

type MockServerUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerUseCase) EXPECT() *MockServerUseCase_Expecter {
	return &MockServerUseCase_Expecter{mock: &_m.Mock}
}

// ConnectToSlot provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) ConnectToSlot(ctx context.Context, slot int32) error {
	ret := _mock.Called(ctx, slot)

	if len(ret) == 0 {
		panic("no return value specified for ConnectToSlot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = returnFunc(ctx, slot)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerUseCase_ConnectToSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectToSlot'
type MockServerUseCase_ConnectToSlot_Call struct {
	*mock.Call
}

// ConnectToSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - slot int32
func (_e *MockServerUseCase_Expecter) ConnectToSlot(ctx interface{}, slot interface{}) *MockServerUseCase_ConnectToSlot_Call {
	return &MockServerUseCase_ConnectToSlot_Call{Call: _e.mock.On("ConnectToSlot", ctx, slot)}
}

func (_c *MockServerUseCase_ConnectToSlot_Call) Run(run func(ctx context.Context, slot int32)) *MockServerUseCase_ConnectToSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerUseCase_ConnectToSlot_Call) Return(err error) *MockServerUseCase_ConnectToSlot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerUseCase_ConnectToSlot_Call) RunAndReturn(run func(ctx context.Context, slot int32) error) *MockServerUseCase_ConnectToSlot_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveClient provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) GetActiveClient(ctx context.Context) *domain.Client {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveClient")
	}

	var r0 *domain.Client
	if returnFunc, ok := ret.Get(0).(func(context.Context) *domain.Client); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	return r0
}

// MockServerUseCase_GetActiveClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveClient'
type MockServerUseCase_GetActiveClient_Call struct {
	*mock.Call
}

// GetActiveClient is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerUseCase_Expecter) GetActiveClient(ctx interface{}) *MockServerUseCase_GetActiveClient_Call {
	return &MockServerUseCase_GetActiveClient_Call{Call: _e.mock.On("GetActiveClient", ctx)}
}

func (_c *MockServerUseCase_GetActiveClient_Call) Run(run func(ctx context.Context)) *MockServerUseCase_GetActiveClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_GetActiveClient_Call) Return(client *domain.Client) *MockServerUseCase_GetActiveClient_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockServerUseCase_GetActiveClient_Call) RunAndReturn(run func(ctx context.Context) *domain.Client) *MockServerUseCase_GetActiveClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectedClients provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) GetConnectedClients(ctx context.Context) []domain.Client {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectedClients")
	}

	var r0 []domain.Client
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Client); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Client)
		}
	}
	return r0
}

// MockServerUseCase_GetConnectedClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectedClients'
type MockServerUseCase_GetConnectedClients_Call struct {
	*mock.Call
}

// GetConnectedClients is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerUseCase_Expecter) GetConnectedClients(ctx interface{}) *MockServerUseCase_GetConnectedClients_Call {
	return &MockServerUseCase_GetConnectedClients_Call{Call: _e.mock.On("GetConnectedClients", ctx)}
}

func (_c *MockServerUseCase_GetConnectedClients_Call) Run(run func(ctx context.Context)) *MockServerUseCase_GetConnectedClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_GetConnectedClients_Call) Return(clients []domain.Client) *MockServerUseCase_GetConnectedClients_Call {
	_c.Call.Return(clients)
	return _c
}

func (_c *MockServerUseCase_GetConnectedClients_Call) RunAndReturn(run func(ctx context.Context) []domain.Client) *MockServerUseCase_GetConnectedClients_Call {
	_c.Call.Return(run)
	return _c
}

// GetNetworkServer provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) GetNetworkServer() out.NetworkServerPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNetworkServer")
	}

	var r0 out.NetworkServerPort
	if returnFunc, ok := ret.Get(0).(func() out.NetworkServerPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(out.NetworkServerPort)
		}
	}
	return r0
}

// MockServerUseCase_GetNetworkServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNetworkServer'
type MockServerUseCase_GetNetworkServer_Call struct {
	*mock.Call
}

// GetNetworkServer is a helper method to define mock.On call
func (_e *MockServerUseCase_Expecter) GetNetworkServer() *MockServerUseCase_GetNetworkServer_Call {
	return &MockServerUseCase_GetNetworkServer_Call{Call: _e.mock.On("GetNetworkServer")}
}

func (_c *MockServerUseCase_GetNetworkServer_Call) Run(run func()) *MockServerUseCase_GetNetworkServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerUseCase_GetNetworkServer_Call) Return(networkServerPort out.NetworkServerPort) *MockServerUseCase_GetNetworkServer_Call {
	_c.Call.Return(networkServerPort)
	return _c
}

func (_c *MockServerUseCase_GetNetworkServer_Call) RunAndReturn(run func() out.NetworkServerPort) *MockServerUseCase_GetNetworkServer_Call {
	_c.Call.Return(run)
	return _c
}

// GetSSHAuthKeysPath provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) GetSSHAuthKeysPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSSHAuthKeysPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockServerUseCase_GetSSHAuthKeysPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSSHAuthKeysPath'
type MockServerUseCase_GetSSHAuthKeysPath_Call struct {
	*mock.Call
}

// GetSSHAuthKeysPath is a helper method to define mock.On call
func (_e *MockServerUseCase_Expecter) GetSSHAuthKeysPath() *MockServerUseCase_GetSSHAuthKeysPath_Call {
	return &MockServerUseCase_GetSSHAuthKeysPath_Call{Call: _e.mock.On("GetSSHAuthKeysPath")}
}

func (_c *MockServerUseCase_GetSSHAuthKeysPath_Call) Run(run func()) *MockServerUseCase_GetSSHAuthKeysPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerUseCase_GetSSHAuthKeysPath_Call) Return(s string) *MockServerUseCase_GetSSHAuthKeysPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockServerUseCase_GetSSHAuthKeysPath_Call) RunAndReturn(run func() string) *MockServerUseCase_GetSSHAuthKeysPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetSSHHostKeyPath provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) GetSSHHostKeyPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSSHHostKeyPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockServerUseCase_GetSSHHostKeyPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSSHHostKeyPath'
type MockServerUseCase_GetSSHHostKeyPath_Call struct {
	*mock.Call
}

// GetSSHHostKeyPath is a helper method to define mock.On call
func (_e *MockServerUseCase_Expecter) GetSSHHostKeyPath() *MockServerUseCase_GetSSHHostKeyPath_Call {
	return &MockServerUseCase_GetSSHHostKeyPath_Call{Call: _e.mock.On("GetSSHHostKeyPath")}
}

func (_c *MockServerUseCase_GetSSHHostKeyPath_Call) Run(run func()) *MockServerUseCase_GetSSHHostKeyPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerUseCase_GetSSHHostKeyPath_Call) Return(s string) *MockServerUseCase_GetSSHHostKeyPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockServerUseCase_GetSSHHostKeyPath_Call) RunAndReturn(run func() string) *MockServerUseCase_GetSSHHostKeyPath_Call {
	_c.Call.Return(run)
	return _c
}

// HandleInputEvent provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) HandleInputEvent(ctx context.Context, event *domain.InputEvent) {
	_mock.Called(ctx, event)
	return
}

// MockServerUseCase_HandleInputEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleInputEvent'
type MockServerUseCase_HandleInputEvent_Call struct {
	*mock.Call
}

// HandleInputEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *domain.InputEvent
func (_e *MockServerUseCase_Expecter) HandleInputEvent(ctx interface{}, event interface{}) *MockServerUseCase_HandleInputEvent_Call {
	return &MockServerUseCase_HandleInputEvent_Call{Call: _e.mock.On("HandleInputEvent", ctx, event)}
}

func (_c *MockServerUseCase_HandleInputEvent_Call) Run(run func(ctx context.Context, event *domain.InputEvent)) *MockServerUseCase_HandleInputEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.InputEvent
		if args[1] != nil {
			arg1 = args[1].(*domain.InputEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerUseCase_HandleInputEvent_Call) Return() *MockServerUseCase_HandleInputEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerUseCase_HandleInputEvent_Call) RunAndReturn(run func(ctx context.Context, event *domain.InputEvent)) *MockServerUseCase_HandleInputEvent_Call {
	_c.Run(run)
	return _c
}

// IsControllingLocal provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) IsControllingLocal(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsControllingLocal")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockServerUseCase_IsControllingLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsControllingLocal'
type MockServerUseCase_IsControllingLocal_Call struct {
	*mock.Call
}

// IsControllingLocal is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerUseCase_Expecter) IsControllingLocal(ctx interface{}) *MockServerUseCase_IsControllingLocal_Call {
	return &MockServerUseCase_IsControllingLocal_Call{Call: _e.mock.On("IsControllingLocal", ctx)}
}

func (_c *MockServerUseCase_IsControllingLocal_Call) Run(run func(ctx context.Context)) *MockServerUseCase_IsControllingLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_IsControllingLocal_Call) Return(b bool) *MockServerUseCase_IsControllingLocal_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockServerUseCase_IsControllingLocal_Call) RunAndReturn(run func(ctx context.Context) bool) *MockServerUseCase_IsControllingLocal_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyShutdown provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) NotifyShutdown(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockServerUseCase_NotifyShutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyShutdown'
type MockServerUseCase_NotifyShutdown_Call struct {
	*mock.Call
}

// NotifyShutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerUseCase_Expecter) NotifyShutdown(ctx interface{}) *MockServerUseCase_NotifyShutdown_Call {
	return &MockServerUseCase_NotifyShutdown_Call{Call: _e.mock.On("NotifyShutdown", ctx)}
}

func (_c *MockServerUseCase_NotifyShutdown_Call) Run(run func(ctx context.Context)) *MockServerUseCase_NotifyShutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_NotifyShutdown_Call) Return() *MockServerUseCase_NotifyShutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerUseCase_NotifyShutdown_Call) RunAndReturn(run func(ctx context.Context)) *MockServerUseCase_NotifyShutdown_Call {
	_c.Run(run)
	return _c
}

// RegisterClient provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) RegisterClient(ctx context.Context, id string, name string, address string) {
	_mock.Called(ctx, id, name, address)
	return
}

// MockServerUseCase_RegisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterClient'
type MockServerUseCase_RegisterClient_Call struct {
	*mock.Call
}

// RegisterClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - address string
func (_e *MockServerUseCase_Expecter) RegisterClient(ctx interface{}, id interface{}, name interface{}, address interface{}) *MockServerUseCase_RegisterClient_Call {
	return &MockServerUseCase_RegisterClient_Call{Call: _e.mock.On("RegisterClient", ctx, id, name, address)}
}

func (_c *MockServerUseCase_RegisterClient_Call) Run(run func(ctx context.Context, id string, name string, address string)) *MockServerUseCase_RegisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServerUseCase_RegisterClient_Call) Return() *MockServerUseCase_RegisterClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerUseCase_RegisterClient_Call) RunAndReturn(run func(ctx context.Context, id string, name string, address string)) *MockServerUseCase_RegisterClient_Call {
	_c.Run(run)
	return _c
}

// SetOnActivity provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) SetOnActivity(callback func(level string, message string)) {
	_mock.Called(callback)
	return
}

// MockServerUseCase_SetOnActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOnActivity'
type MockServerUseCase_SetOnActivity_Call struct {
	*mock.Call
}

// SetOnActivity is a helper method to define mock.On call
//   - callback func(level string, message string)
func (_e *MockServerUseCase_Expecter) SetOnActivity(callback interface{}) *MockServerUseCase_SetOnActivity_Call {
	return &MockServerUseCase_SetOnActivity_Call{Call: _e.mock.On("SetOnActivity", callback)}
}

func (_c *MockServerUseCase_SetOnActivity_Call) Run(run func(callback func(level string, message string))) *MockServerUseCase_SetOnActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(level string, message string)
		if args[0] != nil {
			arg0 = args[0].(func(level string, message string))
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_SetOnActivity_Call) Return() *MockServerUseCase_SetOnActivity_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerUseCase_SetOnActivity_Call) RunAndReturn(run func(callback func(level string, message string))) *MockServerUseCase_SetOnActivity_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerUseCase_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockServerUseCase_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerUseCase_Expecter) Start(ctx interface{}) *MockServerUseCase_Start_Call {
	return &MockServerUseCase_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockServerUseCase_Start_Call) Run(run func(ctx context.Context)) *MockServerUseCase_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_Start_Call) Return(err error) *MockServerUseCase_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerUseCase_Start_Call) RunAndReturn(run func(ctx context.Context) error) *MockServerUseCase_Start_Call {
	_c.Call.Return(run)
	return _c
}

// StartNetworking provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) StartNetworking(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for StartNetworking")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerUseCase_StartNetworking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartNetworking'
type MockServerUseCase_StartNetworking_Call struct {
	*mock.Call
}

// StartNetworking is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerUseCase_Expecter) StartNetworking(ctx interface{}) *MockServerUseCase_StartNetworking_Call {
	return &MockServerUseCase_StartNetworking_Call{Call: _e.mock.On("StartNetworking", ctx)}
}

func (_c *MockServerUseCase_StartNetworking_Call) Run(run func(ctx context.Context)) *MockServerUseCase_StartNetworking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_StartNetworking_Call) Return(err error) *MockServerUseCase_StartNetworking_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerUseCase_StartNetworking_Call) RunAndReturn(run func(ctx context.Context) error) *MockServerUseCase_StartNetworking_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) Stop(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerUseCase_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockServerUseCase_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerUseCase_Expecter) Stop(ctx interface{}) *MockServerUseCase_Stop_Call {
	return &MockServerUseCase_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *MockServerUseCase_Stop_Call) Run(run func(ctx context.Context)) *MockServerUseCase_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_Stop_Call) Return(err error) *MockServerUseCase_Stop_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerUseCase_Stop_Call) RunAndReturn(run func(ctx context.Context) error) *MockServerUseCase_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// SwitchToClient provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) SwitchToClient(ctx context.Context, clientID string) error {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for SwitchToClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerUseCase_SwitchToClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchToClient'
type MockServerUseCase_SwitchToClient_Call struct {
	*mock.Call
}

// SwitchToClient is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *MockServerUseCase_Expecter) SwitchToClient(ctx interface{}, clientID interface{}) *MockServerUseCase_SwitchToClient_Call {
	return &MockServerUseCase_SwitchToClient_Call{Call: _e.mock.On("SwitchToClient", ctx, clientID)}
}

func (_c *MockServerUseCase_SwitchToClient_Call) Run(run func(ctx context.Context, clientID string)) *MockServerUseCase_SwitchToClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerUseCase_SwitchToClient_Call) Return(err error) *MockServerUseCase_SwitchToClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerUseCase_SwitchToClient_Call) RunAndReturn(run func(ctx context.Context, clientID string) error) *MockServerUseCase_SwitchToClient_Call {
	_c.Call.Return(run)
	return _c
}

// SwitchToLocal provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) SwitchToLocal(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SwitchToLocal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerUseCase_SwitchToLocal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchToLocal'
type MockServerUseCase_SwitchToLocal_Call struct {
	*mock.Call
}

// SwitchToLocal is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerUseCase_Expecter) SwitchToLocal(ctx interface{}) *MockServerUseCase_SwitchToLocal_Call {
	return &MockServerUseCase_SwitchToLocal_Call{Call: _e.mock.On("SwitchToLocal", ctx)}
}

func (_c *MockServerUseCase_SwitchToLocal_Call) Run(run func(ctx context.Context)) *MockServerUseCase_SwitchToLocal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_SwitchToLocal_Call) Return(err error) *MockServerUseCase_SwitchToLocal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerUseCase_SwitchToLocal_Call) RunAndReturn(run func(ctx context.Context) error) *MockServerUseCase_SwitchToLocal_Call {
	_c.Call.Return(run)
	return _c
}

// SwitchToNext provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) SwitchToNext(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SwitchToNext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerUseCase_SwitchToNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchToNext'
type MockServerUseCase_SwitchToNext_Call struct {
	*mock.Call
}

// SwitchToNext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerUseCase_Expecter) SwitchToNext(ctx interface{}) *MockServerUseCase_SwitchToNext_Call {
	return &MockServerUseCase_SwitchToNext_Call{Call: _e.mock.On("SwitchToNext", ctx)}
}

func (_c *MockServerUseCase_SwitchToNext_Call) Run(run func(ctx context.Context)) *MockServerUseCase_SwitchToNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_SwitchToNext_Call) Return(err error) *MockServerUseCase_SwitchToNext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerUseCase_SwitchToNext_Call) RunAndReturn(run func(ctx context.Context) error) *MockServerUseCase_SwitchToNext_Call {
	_c.Call.Return(run)
	return _c
}

// SwitchToPrevious provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) SwitchToPrevious(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SwitchToPrevious")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServerUseCase_SwitchToPrevious_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwitchToPrevious'
type MockServerUseCase_SwitchToPrevious_Call struct {
	*mock.Call
}

// SwitchToPrevious is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerUseCase_Expecter) SwitchToPrevious(ctx interface{}) *MockServerUseCase_SwitchToPrevious_Call {
	return &MockServerUseCase_SwitchToPrevious_Call{Call: _e.mock.On("SwitchToPrevious", ctx)}
}

func (_c *MockServerUseCase_SwitchToPrevious_Call) Run(run func(ctx context.Context)) *MockServerUseCase_SwitchToPrevious_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServerUseCase_SwitchToPrevious_Call) Return(err error) *MockServerUseCase_SwitchToPrevious_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServerUseCase_SwitchToPrevious_Call) RunAndReturn(run func(ctx context.Context) error) *MockServerUseCase_SwitchToPrevious_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterClient provides a mock function for the type MockServerUseCase
func (_mock *MockServerUseCase) UnregisterClient(ctx context.Context, id string) {
	_mock.Called(ctx, id)
	return
}

// MockServerUseCase_UnregisterClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterClient'
type MockServerUseCase_UnregisterClient_Call struct {
	*mock.Call
}

// UnregisterClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockServerUseCase_Expecter) UnregisterClient(ctx interface{}, id interface{}) *MockServerUseCase_UnregisterClient_Call {
	return &MockServerUseCase_UnregisterClient_Call{Call: _e.mock.On("UnregisterClient", ctx, id)}
}

func (_c *MockServerUseCase_UnregisterClient_Call) Run(run func(ctx context.Context, id string)) *MockServerUseCase_UnregisterClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerUseCase_UnregisterClient_Call) Return() *MockServerUseCase_UnregisterClient_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerUseCase_UnregisterClient_Call) RunAndReturn(run func(ctx context.Context, id string)) *MockServerUseCase_UnregisterClient_Call {
	_c.Run(run)
	return _c
}
