# golangci-lint configuration
version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - revive
    - misspell
    - bodyclose
    - gocritic
    - gosec
    - unconvert

linters-settings:
  revive:
    rules:
      - name: blank-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: var-naming
      - name: receiver-naming

  govet:
    enable-all: true

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

issues:
  exclude-files:
    - ".*\\.pb\\.go$"